// ========================================
// prisma/seeds/product.seed.js
// ========================================

const prisma = require("../client");

async function productSeed() {

    const company =
        await prisma.company.findFirst();

    if (!company) {

        throw new Error(
            "No existe ninguna empresa. Ejecuta admin.seed primero."
        );

    }

    const category =
        await prisma.category.findFirst();

    if (!category) {

        throw new Error(
            "No existe ninguna categoría. Ejecuta category.seed primero."
        );

    }

    const unit =
        await prisma.unit.findFirst({

            where: {
                type: "UNIT"
            }

        });

    if (!unit) {

        throw new Error(
            "No existe la unidad UNIT. Ejecuta unit.seed primero."
        );

    }

    await prisma.product.createMany({

        data: [
            // === BEBIDAS ===
            {
                name: "Coca Cola 500ml",
                description: "Bebida gaseosa Coca Cola botella de 500ml",
                sku: "COCA-500",
                barcode: "775123450001",
                purchasePrice: 2.20,
                salePrice: 3.50,
                costPrice: 2.20,
                profitAmount: 1.30,
                profitMargin: 59.09,
                minStock: 10,
                maxStock: 100,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Inca Kola 1.5L",
                description: "Bebida gaseosa Inca Kola botella de 1.5 litros",
                sku: "INKA-1.5L",
                barcode: "775123450003",
                purchasePrice: 4.50,
                salePrice: 6.20,
                costPrice: 4.50,
                profitAmount: 1.70,
                profitMargin: 37.78,
                minStock: 15,
                maxStock: 80,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Agua San Mateo 600ml",
                description: "Agua mineral de manantial sin gas 600ml",
                sku: "SMATEO-600",
                barcode: "775123450004",
                purchasePrice: 1.10,
                salePrice: 2.00,
                costPrice: 1.10,
                profitAmount: 0.90,
                profitMargin: 81.82,
                minStock: 20,
                maxStock: 150,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Jugos Frugos Valle Durazno 1L",
                description: "Néctar de durazno Frugos del Valle 1 litro",
                sku: "FRUG-DUR-1L",
                barcode: "775123450005",
                purchasePrice: 3.20,
                salePrice: 4.80,
                costPrice: 3.20,
                profitAmount: 1.60,
                profitMargin: 50.00,
                minStock: 8,
                maxStock: 50,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Sporade Lifemint 500ml",
                description: "Bebida hidratante sabor a menta refrescante",
                sku: "SPOR-LM-500",
                barcode: "775123450006",
                purchasePrice: 1.80,
                salePrice: 3.00,
                costPrice: 1.80,
                profitAmount: 1.20,
                profitMargin: 66.67,
                minStock: 12,
                maxStock: 60,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === ABARROTES BÁSICOS ===
            {
                name: "Arroz Costeño 5kg",
                description: "Arroz superior Costeño bolsa de 5kg",
                sku: "ARROZ-5KG",
                barcode: "775123450002",
                purchasePrice: 18.50,
                salePrice: 24.90,
                costPrice: 18.50,
                profitAmount: 6.40,
                profitMargin: 34.59,
                minStock: 5,
                maxStock: 50,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Azúcar Rubia Cartavio 1kg",
                description: "Azúcar rubia doméstica de alta pureza 1kg",
                sku: "AZUCAR-1KG",
                barcode: "775123450007",
                purchasePrice: 3.40,
                salePrice: 4.50,
                costPrice: 3.40,
                profitAmount: 1.10,
                profitMargin: 32.35,
                minStock: 10,
                maxStock: 70,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Aceite Vegetal Primor 1L",
                description: "Aceite vegetal premium Primor botella de 1 litro",
                sku: "ACEITE-PRI-1L",
                barcode: "775123450008",
                purchasePrice: 7.90,
                salePrice: 10.50,
                costPrice: 7.90,
                profitAmount: 2.60,
                profitMargin: 32.91,
                minStock: 8,
                maxStock: 60,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Fideos Don Vittorio Spaguetti 1kg",
                description: "Fideos de sémola de trigo duro Spaguetti 1kg",
                sku: "FIDE-DV-1KG",
                barcode: "775123450009",
                purchasePrice: 4.10,
                salePrice: 5.80,
                costPrice: 4.10,
                profitAmount: 1.70,
                profitMargin: 41.46,
                minStock: 15,
                maxStock: 100,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Sal Mesa Yodada Flúor 1kg",
                description: "Sal de mesa refinada yodada y fluorada 1kg",
                sku: "SAL-MESA-1KG",
                barcode: "775123450010",
                purchasePrice: 1.20,
                salePrice: 1.90,
                costPrice: 1.20,
                profitAmount: 0.70,
                profitMargin: 58.33,
                minStock: 5,
                maxStock: 40,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === LÁCTEOS Y DERIVADOS ===
            {
                name: "Leche Evaporada Gloria Azul 400g",
                description: "Leche evaporada entera Gloria lata tradicional",
                sku: "LECHE-GLO-AZU",
                barcode: "775123450011",
                purchasePrice: 3.30,
                salePrice: 4.20,
                costPrice: 3.30,
                profitAmount: 0.90,
                profitMargin: 27.27,
                minStock: 24,
                maxStock: 200,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Yogurt Gloria Fresa 1kg",
                description: "Yogurt bebible sabor fresa botella de 1kg",
                sku: "YOG-GLO-FRE-1K",
                barcode: "775123450012",
                purchasePrice: 5.50,
                salePrice: 7.50,
                costPrice: 5.50,
                profitAmount: 2.00,
                profitMargin: 36.36,
                minStock: 6,
                maxStock: 30,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Mantequilla Gloria con Sal 200g",
                description: "Mantequilla de leche de vaca con sal tableta 200g",
                sku: "MANT-GLO-200",
                barcode: "775123450013",
                purchasePrice: 4.80,
                salePrice: 6.50,
                costPrice: 4.80,
                profitAmount: 1.70,
                profitMargin: 35.42,
                minStock: 5,
                maxStock: 25,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Queso Edam Laive Rebanado 200g",
                description: "Queso tipo Edam laminado en empaque sellado",
                sku: "QUESO-EDAM-200",
                barcode: "775123450014",
                purchasePrice: 7.20,
                salePrice: 9.90,
                costPrice: 7.20,
                profitAmount: 2.70,
                profitMargin: 37.50,
                minStock: 4,
                maxStock: 20,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === CONSERVAS Y SALSAS ===
            {
                name: "Trozos de Atún Real en Aceite",
                description: "Conserva de trozos de atún en aceite vegetal 170g",
                sku: "ATUN-REAL-OIL",
                barcode: "775123450015",
                purchasePrice: 4.20,
                salePrice: 5.90,
                costPrice: 4.20,
                profitAmount: 1.70,
                profitMargin: 40.48,
                minStock: 12,
                maxStock: 80,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Mayonesa Alacena Doypack 190g",
                description: "Mayonesa Alacena con un toque de limón de 190g",
                sku: "MAYO-ALA-190",
                barcode: "775123450016",
                purchasePrice: 3.50,
                salePrice: 5.00,
                costPrice: 3.50,
                profitAmount: 1.50,
                profitMargin: 42.86,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Salsa de Tomate Pomarola 150g",
                description: "Salsa de tomate lista para pastas Pomarola 150g",
                sku: "SALSA-POMA-150",
                barcode: "775123450017",
                purchasePrice: 1.40,
                salePrice: 2.20,
                costPrice: 1.40,
                profitAmount: 0.80,
                profitMargin: 57.14,
                minStock: 15,
                maxStock: 60,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === DESAYUNO ===
            {
                name: "Café Altomayo Instantáneo 160g",
                description: "Café instantáneo clásico Altomayo frasco 160g",
                sku: "CAFE-ALTO-160",
                barcode: "775123450018",
                purchasePrice: 11.50,
                salePrice: 15.90,
                costPrice: 11.50,
                profitAmount: 4.40,
                profitMargin: 38.26,
                minStock: 5,
                maxStock: 30,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Milo en Polvo Doypack 400g",
                description: "Modificador de leche Milo activ-go bolsa 400g",
                sku: "MILO-DOY-400",
                barcode: "775123450019",
                purchasePrice: 9.80,
                salePrice: 13.50,
                costPrice: 9.80,
                profitAmount: 3.70,
                profitMargin: 37.76,
                minStock: 6,
                maxStock: 40,
                requiresExpiration: true,
                trackBatches: true,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Avena 3 Ositos Qwaker 350g",
                description: "Avena en hojuelas precocidas tradicional bolsa",
                sku: "AVEN-3OSI-350",
                barcode: "775123450020",
                purchasePrice: 2.60,
                salePrice: 3.80,
                costPrice: 2.60,
                profitAmount: 1.20,
                profitMargin: 46.15,
                minStock: 10,
                maxStock: 60,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Mermelada Fanny Fresa Glass 310g",
                description: "Mermelada de fresa Fanny frasco de vidrio 310g",
                sku: "MERM-FAN-310",
                barcode: "775123450021",
                purchasePrice: 3.90,
                salePrice: 5.50,
                costPrice: 3.90,
                profitAmount: 1.60,
                profitMargin: 41.03,
                minStock: 6,
                maxStock: 36,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === SNACKS Y GOLOSINAS ===
            {
                name: "Papitas Lays Clásicas 150g",
                description: "Papas fritas cortadas finas con sal bolsa familiar",
                sku: "LAYS-CLAS-150",
                barcode: "775123450022",
                purchasePrice: 4.50,
                salePrice: 6.50,
                costPrice: 4.50,
                profitAmount: 2.00,
                profitMargin: 44.44,
                minStock: 8,
                maxStock: 40,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Doritos Mega Queso 150g",
                description: "Tortillas de maíz sabor a queso intenso",
                sku: "DORI-QSO-150",
                barcode: "775123450023",
                purchasePrice: 4.50,
                salePrice: 6.50,
                costPrice: 4.50,
                profitAmount: 2.00,
                profitMargin: 44.44,
                minStock: 8,
                maxStock: 40,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Galletas Casino Fresa Pack x6",
                description: "Pack de 6 unidades de galletas rellenas sabor fresa",
                sku: "CASI-FRE-PX6",
                barcode: "775123450024",
                purchasePrice: 3.10,
                salePrice: 4.50,
                costPrice: 3.10,
                profitAmount: 1.40,
                profitMargin: 45.16,
                minStock: 12,
                maxStock: 72,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Galletas Soda San Jorge Pack x6",
                description: "Galletas de soda saladas crujientes multipack",
                sku: "SODA-SJOR-PX6",
                barcode: "775123450025",
                purchasePrice: 2.50,
                salePrice: 3.80,
                costPrice: 2.50,
                profitAmount: 1.30,
                profitMargin: 52.00,
                minStock: 15,
                maxStock: 90,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Chocolate Sublime Extragrande 50g",
                description: "Chocolate con leche y trozos de maní emblemático",
                sku: "SUBLIME-XG-50",
                barcode: "775123450026",
                purchasePrice: 1.40,
                salePrice: 2.20,
                costPrice: 1.40,
                profitAmount: 0.80,
                profitMargin: 57.14,
                minStock: 20,
                maxStock: 120,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === CUIDADO PERSONAL ===
            {
                name: "Shampoo Head & Shoulders Mentol 375ml",
                description: "Shampoo control caspa acción mentol refrescante",
                sku: "HS-MENT-375",
                barcode: "775123450027",
                purchasePrice: 13.50,
                salePrice: 18.90,
                costPrice: 13.50,
                profitAmount: 5.40,
                profitMargin: 40.00,
                minStock: 6,
                maxStock: 30,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Crema Dental Colgate Triple Acción 75ml",
                description: "Pasta dental protección, blancura y frescura",
                sku: "COLG-TRIP-75",
                barcode: "775123450028",
                purchasePrice: 3.20,
                salePrice: 4.80,
                costPrice: 3.20,
                profitAmount: 1.60,
                profitMargin: 50.00,
                minStock: 10,
                maxStock: 60,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Jabón de Tocador Protex Aloe 110g",
                description: "Jabón antibacterial con extracto de aloe vera",
                sku: "PROT-ALOE-110",
                barcode: "775123450029",
                purchasePrice: 2.10,
                salePrice: 3.20,
                costPrice: 2.10,
                profitAmount: 1.10,
                profitMargin: 52.38,
                minStock: 12,
                maxStock: 72,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Desodorante Rexona Clinical Hombre 48g",
                description: "Antitranspirante en crema máxima protección",
                sku: "REX-CLIN-HOM",
                barcode: "775123450030",
                purchasePrice: 14.20,
                salePrice: 19.90,
                costPrice: 14.20,
                profitAmount: 5.70,
                profitMargin: 40.14,
                minStock: 4,
                maxStock: 24,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Papel Higiénico Elite Doble Hoja x4",
                description: "Paquete de 4 rollos de papel higiénico suave",
                sku: "ELITE-DH-X4",
                barcode: "775123450031",
                purchasePrice: 4.80,
                salePrice: 6.90,
                costPrice: 4.80,
                profitAmount: 2.10,
                profitMargin: 43.75,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === LIMPIEZA DEL HOGAR ===
            {
                name: "Detergente Bolívar Flores de Humo 800g",
                description: "Detergente en polvo para lavado de ropa a mano o máquina",
                sku: "BOLI-FLOR-800",
                barcode: "775123450032",
                purchasePrice: 7.40,
                salePrice: 10.20,
                costPrice: 7.40,
                profitAmount: 2.80,
                profitMargin: 37.84,
                minStock: 8,
                maxStock: 40,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Lavavajilla Líquido Ayudín Limón 500ml",
                description: "Jabón líquido concentrado arrancagrasa sabor limón",
                sku: "AYUD-LIQ-500",
                barcode: "775123450033",
                purchasePrice: 4.10,
                salePrice: 5.80,
                costPrice: 4.10,
                profitAmount: 1.70,
                profitMargin: 41.46,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Cloro Tradicional Clorox 1L",
                description: "Desinfectante y blanqueador de superficies botella 1L",
                sku: "CLOROX-TRAD-1L",
                barcode: "775123450034",
                purchasePrice: 2.90,
                salePrice: 4.20,
                costPrice: 2.90,
                profitAmount: 1.30,
                profitMargin: 44.83,
                minStock: 12,
                maxStock: 60,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Limpiador Poett Lavanda 900ml",
                description: "Limpiador líquido para pisos fragancia lavanda",
                sku: "POETT-LAV-900",
                barcode: "775123450035",
                purchasePrice: 3.80,
                salePrice: 5.50,
                costPrice: 3.80,
                profitAmount: 1.70,
                profitMargin: 44.74,
                minStock: 8,
                maxStock: 48,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Esponja Scotch-Brite Multiuso x2",
                description: "Pack doble de esponjas de fibra verde y amarilla",
                sku: "SCOTCH-MULTI-2",
                barcode: "775123450036",
                purchasePrice: 2.20,
                salePrice: 3.50,
                costPrice: 2.20,
                profitAmount: 1.30,
                profitMargin: 59.09,
                minStock: 15,
                maxStock: 75,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },

            // === COMPLEMENTOS, CONDIMENTOS Y VARIOS ===
            {
                name: "Ají No Moto Sazonador 100g",
                description: "Monoglutamato de sodio sazonador umami bolsa 100g",
                sku: "AJINO-MOTO-100",
                barcode: "775123450037",
                purchasePrice: 2.00,
                salePrice: 3.00,
                costPrice: 2.00,
                profitAmount: 1.00,
                profitMargin: 50.00,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Vinagre Blanco Primor 500ml",
                description: "Vinagre blanco ideal para cocina y ensaladas",
                sku: "VINA-PRI-500",
                barcode: "775123450038",
                purchasePrice: 1.60,
                salePrice: 2.50,
                costPrice: 1.60,
                profitAmount: 0.90,
                profitMargin: 56.25,
                minStock: 6,
                maxStock: 30,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Gelatina Royal Fresa 150g",
                description: "Polvo para preparar gelatina sabor a fresa",
                sku: "GELA-ROY-FRE",
                barcode: "775123450039",
                purchasePrice: 2.30,
                salePrice: 3.50,
                costPrice: 2.30,
                profitAmount: 1.20,
                profitMargin: 52.17,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Té Filtrante Hornimans Manzanilla x25",
                description: "Caja de 25 bolsitas filtrantes de manzanilla pura",
                sku: "HORN-MANZ-X25",
                barcode: "775123450040",
                purchasePrice: 2.80,
                salePrice: 4.20,
                costPrice: 2.80,
                profitAmount: 1.40,
                profitMargin: 50.00,
                minStock: 8,
                maxStock: 40,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Pañales Huggies Natural Care G x30",
                description: "Pañales desechables talle Grande etapa 3 x 30 unidades",
                sku: "HUGG-NC-G30",
                barcode: "775123450041",
                purchasePrice: 28.50,
                salePrice: 38.00,
                costPrice: 28.50,
                profitAmount: 9.50,
                profitMargin: 33.33,
                minStock: 3,
                maxStock: 15,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Toallas Higiénicas Nosotras Tela x10",
                description: "Toallas sanitarias normales con alas tipo tela suave",
                sku: "NOS-TELA-X10",
                barcode: "775123450042",
                purchasePrice: 3.90,
                salePrice: 5.50,
                costPrice: 3.90,
                profitAmount: 1.60,
                profitMargin: 41.03,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Quaker Instantáneo Manzana Canela 400g",
                description: "Avena instantánea sabor manzana y canela bolsa",
                sku: "QUAK-MANZ-400",
                barcode: "775123450043",
                purchasePrice: 4.90,
                salePrice: 6.90,
                costPrice: 4.90,
                profitAmount: 2.00,
                profitMargin: 40.82,
                minStock: 6,
                maxStock: 36,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Cereal Angel Flakes Bolsa 500g",
                description: "Hojuelas de maíz tostadas azucaradas empaque familiar",
                sku: "ANGEL-FLAK-500",
                barcode: "775123450044",
                purchasePrice: 7.20,
                salePrice: 10.50,
                costPrice: 7.20,
                profitAmount: 3.30,
                profitMargin: 45.83,
                minStock: 5,
                maxStock: 30,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Ketchup Alacena Doypack 190g",
                description: "Salsa de tomate Ketchup Alacena receta casera",
                sku: "KET-ALA-190",
                barcode: "775123450045",
                purchasePrice: 3.20,
                salePrice: 4.60,
                costPrice: 3.20,
                profitAmount: 1.40,
                profitMargin: 43.75,
                minStock: 10,
                maxStock: 40,
                requiresExpiration: true,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Suavizante Downy Frescura Pureza 800ml",
                description: "Suavizante concentrado para ropa aroma prolongado",
                sku: "DOWNY-FP-800",
                barcode: "775123450046",
                purchasePrice: 8.50,
                salePrice: 12.50,
                costPrice: 8.50,
                profitAmount: 4.00,
                profitMargin: 47.06,
                minStock: 6,
                maxStock: 30,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Insecticida Sapolio Mata Todo 360ml",
                description: "Aerosol insecticida eficaz contra moscas y mosquitos",
                sku: "SAPO-INSE-360",
                barcode: "775123450047",
                purchasePrice: 5.90,
                salePrice: 8.50,
                costPrice: 5.90,
                profitAmount: 2.60,
                profitMargin: 44.07,
                minStock: 5,
                maxStock: 25,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Pilas Duracell AA Pack x4",
                description: "Pilas alcalinas de larga duración tamaño AA",
                sku: "DURA-AA-X4",
                barcode: "775123450048",
                purchasePrice: 11.20,
                salePrice: 16.50,
                costPrice: 11.20,
                profitAmount: 5.30,
                profitMargin: 47.32,
                minStock: 5,
                maxStock: 30,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: true,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Fósforos Inti Caja Pack x10",
                description: "Paquete contenedor de 10 cajas pequeñas de fósforos",
                sku: "FOSF-INTI-X10",
                barcode: "775123450049",
                purchasePrice: 1.50,
                salePrice: 2.50,
                costPrice: 1.50,
                profitAmount: 1.00,
                profitMargin: 66.67,
                minStock: 10,
                maxStock: 50,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            },
            {
                name: "Encendedor Bic Clásico Grande",
                description: "Encendedor de bolsillo descartable de gas regulado",
                sku: "BIC-LARGE-ENC",
                barcode: "775123450050",
                purchasePrice: 2.10,
                salePrice: 3.50,
                costPrice: 2.10,
                profitAmount: 1.40,
                profitMargin: 66.67,
                minStock: 8,
                maxStock: 40,
                requiresExpiration: false,
                trackBatches: false,
                isFeatured: false,
                companyId: company.id,
                categoryId: category.id,
                unitId: unit.id
            }
        ],

        skipDuplicates: true

    });

    console.log(
        "✅ Productos creados correctamente"
    );

}

module.exports = {
    productSeed
};