name: Main CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml

  docker:
    needs:
      - backend
      - frontend
    uses: ./.github/workflows/docker.yml
    # Le pasamos los secretos al workflow de docker para que pueda usarlos
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}